In [1]:
import numpy as np

In [3]:
from sklearn.datasets import load_diabetes

In [8]:
x,y = load_diabetes(return_X_y=True)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state = 2)

In [11]:
x_train.shape

(353, 10)

In [38]:
class meraLR:
    
    def __init__(self):
        self.coef_=None
        self.intercept_=None

    def fit(self,x_train,y_train):
        x_train = np.insert(x_train,0,1,axis=1)
        # calculate the coefficients
        betas = np.linalg.inv(np.dot(x_train.T, x_train)).dot(x_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,x_test):
        y_pred = self.intercept_ + np.dot(x_test, self.coef_)
        return y_pred
        

In [39]:
lr = meraLR()

In [40]:
lr.fit(x_train,y_train)

In [13]:
x_train

array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [14]:
np.insert(x_train,0,1,axis=1)

array([[ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [ 1.        , -0.00914709, -0.04464164, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 1.        ,  0.02354575,  0.05068012, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 1.        ,  0.06350368,  0.05068012, ..., -0.00259226,
         0.08449153, -0.01764613],
       [ 1.        , -0.05273755,  0.05068012, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 1.        ,  0.00175052,  0.05068012, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [15]:
np.insert(x_train,0,1,axis=1).shape

(353, 11)

In [20]:
x_test

array([[ 0.06713621, -0.04464164,  0.00349435,  0.03564379,  0.0493413 ,
         0.03125356,  0.07072993, -0.03949338, -0.00061174,  0.01963284],
       [-0.07816532,  0.05068012,  0.07786339,  0.05285804,  0.07823631,
         0.0644473 ,  0.02655027, -0.00259226,  0.04067283, -0.00936191],
       [ 0.04170844,  0.05068012, -0.01482845, -0.01713512, -0.00569682,
         0.00839372, -0.01394774, -0.00185424, -0.01189685,  0.00306441],
       [-0.04547248, -0.04464164, -0.04824063, -0.01944183, -0.00019301,
        -0.01603186,  0.06704829, -0.03949338, -0.02479543,  0.01963284],
       [ 0.0090156 ,  0.05068012,  0.06924089,  0.05974375,  0.01769438,
        -0.02323427, -0.04708248,  0.03430886,  0.10329702,  0.07348023],
       [ 0.03444337,  0.05068012,  0.12528712,  0.02875809, -0.05385517,
        -0.01290037, -0.10230705,  0.1081111 ,  0.00027248,  0.02791705],
       [-0.03457486, -0.04464164, -0.05901875,  0.00121528, -0.05385517,
        -0.07803525,  0.06704829, -0.0763945 

In [21]:
x_test.shape

(89, 10)

In [45]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [41]:
lr.predict(x_test)

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [42]:
y_pred = lr.predict(x_test)

In [43]:
from sklearn.metrics import r2_score

In [44]:
r2_score(y_test, y_pred)

0.4399338661568968

In [47]:
lr.intercept_

np.float64(151.88331005254167)