In [2]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score

In [3]:
import numpy as np

In [4]:
X,y = load_diabetes(return_X_y=True)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=4)

In [6]:
reg = Ridge(alpha=0.1, solver='cholesky')

In [7]:
reg.fit(X_train, y_train)

Ridge(alpha=0.1, solver='cholesky')

In [8]:
y_pred = reg.predict(X_test)

In [9]:
r2_score(y_test, y_pred)

0.46931288533098037

In [10]:
reg.coef_

array([  44.02063391, -241.69329987,  452.98665299,  332.04420177,
        -76.33686744,  -68.52143809, -164.98809083,  149.96908118,
        431.61347417,   58.51862681])

In [11]:
reg.intercept_

np.float64(150.89053425602808)

# Creating own Ridge Class

In [18]:
np.insert(X_train, 0, 1, axis=1)

array([[ 1.        ,  0.0090156 , -0.04464164, ...,  0.02323852,
         0.05568623,  0.10661708],
       [ 1.        ,  0.03081083,  0.05068012, ...,  0.05755657,
         0.0354587 ,  0.08590655],
       [ 1.        ,  0.01628068, -0.04464164, ..., -0.03949338,
        -0.05947118, -0.06735141],
       ...,
       [ 1.        ,  0.04170844,  0.05068012, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [ 1.        ,  0.01628068,  0.05068012, ..., -0.03949338,
         0.01703607,  0.00720652],
       [ 1.        ,  0.04897352,  0.05068012, ...,  0.07120998,
         0.03243232,  0.04862759]])

In [19]:
X_train

array([[ 0.0090156 , -0.04464164,  0.05522933, ...,  0.02323852,
         0.05568623,  0.10661708],
       [ 0.03081083,  0.05068012, -0.03422907, ...,  0.05755657,
         0.0354587 ,  0.08590655],
       [ 0.01628068, -0.04464164, -0.06332999, ..., -0.03949338,
        -0.05947118, -0.06735141],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [ 0.01628068,  0.05068012,  0.00996123, ..., -0.03949338,
         0.01703607,  0.00720652],
       [ 0.04897352,  0.05068012,  0.08109682, ...,  0.07120998,
         0.03243232,  0.04862759]])

In [38]:
class MeraRidge:
    def __init__(self, alpha=0.1):
        self.alpha = alpha
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train, y_train):
        X_train = np.insert(X_train, 0, 1, axis=1)
        I = np.identity(X_train.shape[1])
        result = np.linalg.inv(np.dot(X_train.T, X_train) + self.alpha * I).dot(X_train.T).dot(y_train)
        self.intercept_ = result[0]
        self.coef_ = result[1:]

    def predict(self,X_test):
        return np.dot(X_test, self.coef_) + self.intercept_

In [24]:
reg = MeraRidge()

In [25]:
reg.fit(X_train, y_train)

In [26]:
y_pred = reg.predict(X_test)

In [27]:
r2_score(y_test, y_pred)

0.46921361559931885

In [28]:
reg.coef_

array([  44.04252774, -241.72019592,  452.99153345,  332.06044266,
        -76.32617866,  -68.54884462, -165.01664054,  149.93980143,
        431.59483654,   58.54419942])

In [29]:
reg.intercept_

np.float64(150.84762720023167)

## Making the answer exactly same by doing the modification in I, making its 1st 1 also to be 0 so that it does not interfere in intercept term

In [30]:
class MeraRidge:
    def __init__(self, alpha=0.1):
        self.alpha = alpha
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train, y_train):
        X_train = np.insert(X_train, 0, 1, axis=1)
        I = np.identity(X_train.shape[1])
        I[0][0]= 0
        result = np.linalg.inv(np.dot(X_train.T, X_train) + self.alpha * I).dot(X_train.T).dot(y_train)
        self.intercept_ = result[0]
        self.coef_ = result[1:]

    def predict(self,X_test):
        return np.dot(X_test, self.coef_) + self.intercept_

In [31]:
reg = MeraRidge()

In [33]:
reg.fit(X_train, y_train)

In [34]:
y_pred = reg.predict(X_test)

In [35]:
r2_score(y_test, y_pred)

0.46931288533098037

In [36]:
reg.coef_

array([  44.02063391, -241.69329987,  452.98665299,  332.04420177,
        -76.33686744,  -68.52143809, -164.98809083,  149.96908118,
        431.61347417,   58.51862681])

In [37]:
reg.intercept_

np.float64(150.89053425602808)