In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import r2_score
from sklearn.datasets import load_diabetes

In [7]:
X,y = load_diabetes(return_X_y=True)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=4)

In [11]:
reg = SGDRegressor(penalty='l2', max_iter=500, eta0=0.1, learning_rate='constant',alpha=0.001)

In [12]:
reg.fit(X_train,y_train)

SGDRegressor(alpha=0.001, eta0=0.1, learning_rate='constant', max_iter=500)

In [13]:
y_pred = reg.predict(X_test)
r2_score(y_test, y_pred)

0.4427986422510508

In [14]:
reg.coef_

array([  47.57518037, -147.91124503,  362.13230301,  265.3707154 ,
         -5.19622541,  -55.95073197, -169.45372989,  136.41231993,
        321.38205776,  100.28267456])

In [15]:
reg.intercept_

array([146.72505145])

## Gradient descent using Ridge Class

In [16]:
reg1 = Ridge(alpha=0.001, max_iter=500, solver='sparse_cg')

In [17]:
reg1.fit(X_train,y_train)

Ridge(alpha=0.001, max_iter=500, solver='sparse_cg')

In [18]:
y_pred1 = reg1.predict(X_test)

In [21]:
r2_score(y_test, y_pred1)

0.46250101621910966

In [22]:
reg.coef_

array([  47.57518037, -147.91124503,  362.13230301,  265.3707154 ,
         -5.19622541,  -55.95073197, -169.45372989,  136.41231993,
        321.38205776,  100.28267456])

In [25]:
reg.intercept_

array([146.72505145])

## Creating own Ridge Class utilising Gradient Descent

In [34]:
class MeraRidgeGD:
    def __init__(self, epochs, learning_rate, alpha):
        self.epochs=epochs
        self.learning_rate = learning_rate
        self.alpha = alpha
        self.coef_ = None
        self.intercept_= None

    def fit(self, X_train, y_train):
        self.coef_ = np.ones(X_train.shape[1])
        self.intercept_ = 0
        thetha = np.insert(self.coef_, 0, self.intercept_)
        X_train = np.insert(X_train, 0, 1, axis=1)
        for i in range(self.epochs):
            thetha_der = np.dot(X_train.T,X_train).dot(thetha) - np.dot(X_train.T, y_train) + self.alpha*thetha
            thetha = thetha - self.learning_rate * thetha_der
        self.coef_ = thetha[1:]
        self.intercept_ = thetha[0]

    def predict(self,X_test):
        return np.dot(X_test, self.coef_) + self.intercept_

In [52]:
reg2 = MeraRidgeGD(epochs=500, alpha=0.001, learning_rate=0.005)

In [53]:
reg2.fit(X_train, y_train)

In [54]:
y_pred2 = reg2.predict(X_test)

In [55]:
r2_score(y_test,y_pred2)

0.4738018280260914

In [56]:
reg2.coef_

array([  46.65050914, -221.3750037 ,  452.12080647,  325.54248128,
        -29.09464178,  -96.47517735, -190.90017011,  146.32900372,
        400.80267299,   95.09048094])

In [57]:
reg2.intercept_

np.float64(150.86975316713472)