In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [4]:
from sklearn.datasets import load_diabetes

In [5]:
X,y = load_diabetes(return_X_y=True)

In [6]:
X.shape

(442, 10)

In [7]:
y.shape

(442,)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=2)

In [10]:
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [11]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [12]:
reg.intercept_

np.float64(151.88331005254167)

In [13]:
y_pred = reg.predict(X_test)

In [14]:
r2_score(y_test,y_pred)

0.4399338661568969

In [16]:
import random

In [78]:
class MBGDRegressor:
    def __init__(self,batch_size, learning_rate=0.01, epochs=100):
        self.lr = learning_rate
        self.epochs = epochs
        self.coef_ = None
        self.intercept_=None
        self.batch_size = batch_size
    def fit(self,X_train,y_train):
        self.coef_=np.ones(X_train.shape[1])
        self.intercept_ = 0
        for i in range(self.epochs):
            for j in range(int(X_train.shape[0]/self.batch_size)):
                idx = random.sample(range(0,X_train.shape[0]),self.batch_size)
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                intercept_der = -2 * np.mean(y_train[idx]-y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)
                coef_der = -2 * np.dot((y_train[idx]-y_hat),X_train[idx]) / self.batch_size
                self.coef_ = self.coef_ - (self.lr * coef_der)
        print(self.coef_, self.intercept_)
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [79]:
mbgd = MBGDRegressor(batch_size=int(X_train.shape[0]/50), learning_rate=0.01, epochs=100)

In [80]:
mbgd.fit(X_train, y_train)

[ 51.59057561  -1.59569984 165.31075334 124.94634923  40.1220807
  23.45748159 -95.62013416  92.7019212  159.21368023  85.64082485] 152.84379832533946


In [81]:
y_pred = mbgd.predict(X_test)

In [82]:
r2_score(y_test, y_pred)

0.32055700260381026

In [17]:
random.sample(range(0,X_train.shape[0]),10)

[264, 212, 286, 39, 72, 326, 53, 40, 63, 251]

In [18]:
X_train[[264, 212, 286, 39, 72, 326, 53, 40, 63, 251]]

array([[-0.02730979,  0.05068012, -0.01590626, -0.02977038,  0.00393485,
        -0.00068758,  0.04127682, -0.03949338, -0.02364686,  0.01134862],
       [-0.00551455,  0.05068012, -0.04177375, -0.04354178, -0.07999827,
        -0.07615636, -0.03235593, -0.03949338,  0.01022672, -0.00936191],
       [-0.10722563, -0.04464164, -0.07734155, -0.02632753, -0.08962994,
        -0.09619786,  0.02655027, -0.0763945 , -0.04257085, -0.0052198 ],
       [ 0.01991321,  0.05068012, -0.01267283,  0.0700723 , -0.01120063,
         0.00714113, -0.03971921,  0.03430886,  0.00538633,  0.00306441],
       [ 0.02717829,  0.05068012,  0.09403057,  0.09761511, -0.03459183,
        -0.03200243, -0.04340085, -0.00259226,  0.03664373,  0.10661708],
       [ 0.03807591,  0.05068012,  0.00564998,  0.03220094,  0.00668676,
         0.01747503, -0.02499266,  0.03430886,  0.01482098,  0.06105391],
       [ 0.02717829, -0.04464164, -0.00728377, -0.05042748,  0.0754844 ,
         0.05661859,  0.03391355, -0.00259226

In [19]:
X_train[[264, 212, 286, 39, 72, 326, 53, 40, 63, 251]].shape

(10, 10)

In [22]:
X_train.shape

(353, 10)

In [65]:
int((X_train.shape[0]/50))

7

## SCIKIT LEARN IMPLEMENTATION OF MINI BATCH

In [83]:
from sklearn.linear_model import SGDRegressor

In [99]:
sgd = SGDRegressor(learning_rate='constant', eta0=0.1)

In [100]:
batch_size = 35

for i in range(10):
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [101]:
sgd.coef_

array([ 19.53355288,  -0.2657736 ,  80.81663346,  58.74007394,
        14.24044425,   8.69809817, -48.01330751,  45.69627368,
        70.2423574 ,  41.78868233])

In [102]:
sgd.intercept_

array([129.87064155])

In [103]:
r2_score(y_test,y_pred)

0.32055700260381026

In [97]:
X_train.shape[0]

353

In [98]:
X_train.shape[0]/35

10.085714285714285